//******************************************************************
// 
//  Generated by RoboCompDSL
//  
//  File name: Pose.ice
//  Source: Pose.idsl
//
//******************************************************************
#ifndef ROBOCOMPPOSE_ICE
#define ROBOCOMPPOSE_ICE
module RoboCompPose
{
	sequence <byte> img;
	interface Pose
	{
		void sendData (string host, string data, string other);
		void sendImage (string host, img image, string other);
	};
};

#endif
